# Utilitarian compose file to locally run required external services
# required by the builder-server. Just by running `docker-compose up`
# you will have a postgres and an s3 compatible local object storage
# ready to be used.

version: "3.4"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=builder-server
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Database viewer to easily check what is going on inside the database.
  # Allows query execution for reading and writing as well as the display
  # of many other metrics.
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 15432:80

  # Object storage compatible with aws-sdk.
  # Comes with a UI that can be accessed via http://localhost:9001.
  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  # Short lived process in charge of initializing the bucket (if needed) 
  # on start.
  minio-initialize-bucket:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./minio-initialize-bucket-entrypoint.sh:/scripts/entrypoint.sh
    entrypoint: /scripts/entrypoint.sh

volumes:
  postgres_data:
  pgadmin_data:
  minio_data:
