name: Docker

on:
  push:
    branches:
      - 'feat/add-social-emotes'

jobs:
  cd-dev:
    uses: decentraland/actions/.github/workflows/build-quay-main.yml@main
    with:
      service-name: builder-server
      deployment-environment: dev
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
